# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mstrauss <mstrauss@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/02/23 11:29:09 by mstrauss          #+#    #+#              #
#    Updated: 2025/02/24 18:04:24 by mstrauss         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
      - "80:80" # This is needed, because the french apes writing the subjects couldn't peel a banana if their life depended on it
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    # healthcheck:

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"
    environment:
      WORDPRESS_DB_HOST: mariadb
    networks:
      - inception
    # expose:    # Documentation says this is unneccessary, services on the same network can already communicate with docker compose
    #   - "9000"
    volumes:
      - wordpress:/var/www/html
      # - db:/var/lib/mysql  # Doesn't need access to the volume, as its supposed to interact with the db through mariadb service.
    secrets:
      - db_name
      - db_user
      - db_pass
      - db_root_user
      - db_root_pass
      - wp_root_user
      - wp_root_pass

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    restart: always
    expose:
      - "3306"
    # environment:
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_name
      - db_user
      - db_pass
      - db_root_user
      - db_root_pass
      - wp_root_user
      - wp_root_pass


networks:
  inception:
    driver: bridge

volumes:
  db:
  wordpress:

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_pass:
    file: ./secrets/db_pass.txt
  db_root_user:
    file: ./secrets/db_root_user.txt
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  wp_root_user:
    file: ./secrets/wp_root_user.txt
  wp_root_pass:
    file: ./secrets/wp_root_pass.txt